name: Deploy with API Key
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "const API_KEY = '${{ secrets.GEMINI_API_KEY }}';" > api-key.js
        # Lanjutkan dengan build/deploy Anda
